/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.hlidskialf.android.filer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int file_list_item_normal=0x7f020009;
        public static final int file_list_item_yanked=0x7f02000a;
        public static final int filer_icon=0x7f020000;
        public static final int mime_audio=0x7f020001;
        public static final int mime_folder=0x7f020002;
        public static final int mime_generic=0x7f020003;
        public static final int mime_html=0x7f020004;
        public static final int mime_image=0x7f020005;
        public static final int mime_package=0x7f020006;
        public static final int mime_text=0x7f020007;
        public static final int mime_video=0x7f020008;
    }
    public static final class id {
        public static final int button_bar=0x7f070014;
        public static final int button_ok=0x7f070015;
        public static final int button_unyank=0x7f070016;
        public static final int empty=0x7f070006;
        public static final int file_context_menu_delete=0x7f07001c;
        public static final int file_context_menu_open=0x7f07001a;
        public static final int file_context_menu_rename=0x7f07001b;
        public static final int file_context_menu_unyank=0x7f070019;
        public static final int file_context_menu_yank=0x7f070018;
        public static final int mime_button_new=0x7f07000e;
        public static final int mime_list=0x7f07000f;
        public static final int mime_list_item_ext=0x7f07000c;
        public static final int mime_list_item_mime=0x7f07000d;
        public static final int new_mime_extension=0x7f070010;
        public static final int new_mime_mimetype=0x7f070011;
        public static final int options_menu_copy=0x7f07001e;
        public static final int options_menu_help=0x7f070022;
        public static final int options_menu_move=0x7f07001f;
        public static final int options_menu_newdir=0x7f070020;
        public static final int options_menu_prefs=0x7f070021;
        public static final int options_menu_unyank=0x7f07001d;
        public static final int row=0x7f070000;
        public static final int row_icon=0x7f070002;
        public static final int row_mtime=0x7f070005;
        public static final int row_size=0x7f070003;
        public static final int row_text=0x7f070001;
        public static final int row_type=0x7f070004;
        public static final int textentry_splash=0x7f070012;
        public static final int textentry_text=0x7f070013;
        public static final int yank_bar=0x7f070007;
        public static final int yank_bar_buffer=0x7f070008;
        public static final int yank_bar_copy=0x7f070009;
        public static final int yank_bar_delete=0x7f07000b;
        public static final int yank_bar_move=0x7f07000a;
        public static final int yank_buffer_contents=0x7f070017;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int file_list_item=0x7f030001;
        public static final int filer=0x7f030002;
        public static final int mime_list_item=0x7f030003;
        public static final int mimes=0x7f030004;
        public static final int new_mime_dialog=0x7f030005;
        public static final int textentry_dialog=0x7f030006;
        public static final int yank_buffer=0x7f030007;
    }
    public static final class menu {
        public static final int files_context=0x7f060000;
        public static final int options=0x7f060001;
    }
    public static final class string {
        public static final int about=0x7f05000e;
        public static final int about_body=0x7f050010;
        public static final int about_title=0x7f05000f;
        public static final int app_desc=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int app_preferences=0x7f050003;
        public static final int app_version=0x7f050002;
        public static final int back_cdup=0x7f050020;
        public static final int back_cdup_summary=0x7f050021;
        public static final int browse_root=0x7f050022;
        public static final int browse_root_summary=0x7f050023;
        public static final int cancel=0x7f050012;
        public static final int confirm_copy=0x7f05002e;
        public static final int confirm_copy_summary=0x7f05002f;
        public static final int confirm_delete=0x7f050032;
        public static final int confirm_delete_summary=0x7f050033;
        public static final int confirm_move=0x7f050030;
        public static final int confirm_move_summary=0x7f050031;
        public static final int confirms=0x7f05002c;
        public static final int confirms_summary=0x7f05002d;
        public static final int copy=0x7f050018;
        public static final int copy_here=0x7f05001c;
        public static final int default_mime=0x7f05002a;
        public static final int default_mime_summary=0x7f05002b;
        public static final int delete=0x7f05001a;
        public static final int delete_all=0x7f05001b;
        public static final int extension=0x7f050015;
        public static final int file_exists=0x7f050040;
        public static final int help=0x7f05000b;
        public static final int help_message=0x7f05000d;
        public static final int help_title=0x7f05000c;
        public static final int hide_dot_files=0x7f05001e;
        public static final int hide_dot_files_summary=0x7f05001f;
        public static final int home_directory=0x7f050024;
        public static final int home_directory_summary=0x7f050025;
        public static final int mime_ext=0x7f050028;
        public static final int mime_ext_summary=0x7f050029;
        public static final int mimes=0x7f050026;
        public static final int mimes_summary=0x7f050027;
        public static final int mimetype=0x7f050014;
        public static final int move=0x7f050019;
        public static final int move_here=0x7f05001d;
        public static final int new_directory=0x7f05000a;
        public static final int new_mime=0x7f050013;
        public static final int newdir_fail=0x7f05003d;
        public static final int newdir_pass=0x7f05003c;
        public static final int newdir_splash=0x7f05003b;
        public static final int newdir_title=0x7f05003a;
        public static final int ok=0x7f050011;
        public static final int open_as=0x7f050008;
        public static final int preferences=0x7f050004;
        public static final int recursive_delete=0x7f050034;
        public static final int recursive_delete_summary=0x7f050035;
        public static final int rename=0x7f050009;
        public static final int rename_fail=0x7f050039;
        public static final int rename_pass=0x7f050038;
        public static final int rename_splash=0x7f050037;
        public static final int rename_title=0x7f050036;
        public static final int shortcut_name_splash=0x7f05003f;
        public static final int shortcut_name_title=0x7f05003e;
        public static final int shortcut_toast=0x7f050041;
        public static final int unyank=0x7f050006;
        public static final int unyank_all=0x7f050007;
        public static final int yank=0x7f050005;
        public static final int yank_buffer=0x7f050017;
        public static final int yank_buffer_title=0x7f050016;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
